# Generated by Django 4.0.3 on 2022-06-08 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_plans', '0002_alter_mealplan_date_alter_mealplan_recipes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealplan',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
