# Generated by Django 4.0.3 on 2022-06-08 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meal_plans', '0003_alter_mealplan_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealplan',
            name='date',
        ),
    ]
