# Generated by Django 4.0.3 on 2022-06-08 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_plans', '0004_remove_mealplan_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealplan',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
